---
#  loki/config.yaml - Compatible with Loki 2.9.14 (Single Binary with Boltdb-Shipper/Filesystem)

auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

target: all

schema_configs:
  - from: 2020-10-27
    store: boltdb-shipper
    object_store: filesystem
    schema: v12 #  v12 is prima voor 2.9.x
    period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
    retention_period: 24h
  filesystem:
    directory: /tmp/loki/chunks

chunk_store_config:
  max_look_back_period: 24h

compactor:
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 15

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  max_transfer_retries: 0

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_length: 5m
  max_query_series: 5000
  max_query_samples: 5000000

querier:
  default_query_lookback: 6h
  query_timeout: 1m
  max_concurrent_queries: 20
  engine:
    timeout: 1m

ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://localhost
  ring:
    kvstore:
      store: inmemory
    instance_addr: 127.0.0.1
