---
#  loki/config.yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

#  'common' wordt nu 'compactor', 'ingester', 'ruler', 'querier', 'distributor', etc.
#  Voor een simpele setup kunnen we de opslag-config direct onder 'storage' zetten.
storage:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
    retention_period: 24h
  filesystem:
    directory: /tmp/loki/chunks

schema_config:
  configs:
    - from: 2020-10-27
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      #  'period' is vervangen door 'index_period' in de schema_config als je het per index wilt instellen.
      #  Maar voor v11 schema met boltdb-shipper is de retention in 'storage' leidend.
      #  Je kunt 'period' hier gewoon weglaten.

#  Het 'ruler' block is vaak nodig voor inmemory store setups
ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://localhost #  Optioneel, voor alertmanager integratie
  ring:
    kvstore:
      store: inmemory
    instance_addr: 127.0.0.1
  #enable_api: true #  Optioneel, voor rule API

#  De 'ingester' configuratie
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
      instance_addr: 127.0.0.1
    final_sleep: 0s


limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h #  7 dagen

#  Het 'chunk_store_config' block
chunk_store_config:
  max_look_back_period: 24h

#  De 'compactor' configuratie (voor index compaction)
compactor:
  ring:
    kvstore:
      store: inmemory
    instance_addr: 127.0.0.1
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 15

#  De 'distributor' configuratie
distributor:
  ring:
    kvstore:
      store: inmemory
    instance_addr: 127.0.0.1

#  De 'querier' configuratie
querier:
  default_query_lookback: 6h
  query_timeout: 1m
  max_concurrent_queries: 20

#  De 'analytics' configuratie
analytics:
  reporting_enabled: false
