---
#  loki/config.yaml

auth_enabled: false #  Geen authenticatie vereist

server:
  http_listen_port: 3100 #  HTTP API voor Promtail, Grafana
  grpc_listen_port: 9095 #  gRPC voor interne communicatie (optioneel voor single binary)

target: all #  Loki draait alle componenten (ingester, querier, etc.) in één binary

schema_configs: #  Let op: dit is 'schema_configs' (meervoud) in recentere versies
  - from: 2020-10-27
    store: boltdb-shipper #  Opslag voor indexen
    object_store: filesystem #  Opslag voor chunks (logs)
    schema: v12 #  Gebruik v12 schema, standaard voor 2.x
    period: 24h #  Indexperiode, kan gelijk zijn aan retention_period

storage_config: #  De hoofdconfiguratie voor opslag
  boltdb_shipper:
    active_index_directory: /tmp/loki/index #  Waar indexen tijdelijk staan
    cache_location: /tmp/loki/cache #  Cache voor indexen
    retention_period: 24h #  Retentie voor indexen
  filesystem:
    directory: /tmp/loki/chunks #  Waar de feitelijke logdata staat

chunk_store_config:
  max_look_back_period: 24h #  Hoe ver terug je kunt zoeken

compactor:
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 15

ingester:
  lifecycler:
    address: 127.0.0.1 #  Adres van de ingester binnen de container
    ring:
      kvstore:
        store: inmemory #  Gebruik in-memory ring voor single binary
      replication_factor: 1 #  Nodig voor ring, ook al is het single binary
    final_sleep: 0s
  max_transfer_retries: 0 #  Nieuwe toevoeging voor meer robuustheid

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h #  7 dagen (moet groter zijn dan retention_period)
  max_query_length: 5m
  max_query_series: 5000
  max_query_samples: 5000000

querier:
  default_query_lookback: 6h
  query_timeout: 1m
  max_concurrent_queries: 20
  engine: #  De 'engine' sectie is nu wel standaard voor 2.10.0
    timeout: 1m

ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://localhost #  Alleen nodig als je Alertmanager gebruikt
  ring:
    kvstore:
      store: inmemory
    instance_addr: 127.0.0.1
