auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  path_prefix: /tmp/loki
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-27
      store: boltdb-shipper
      object_store: filesystem
      schema: v12
      period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
    retention_period: 24h
    retention_decompress_age_days: 7
  filesystem:
    directory: /tmp/loki/chunks

compactor:
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 15

chunk_store_config:
  max_look_back_period: 0s

ingester:
  wal:
    dir: /tmp/loki/wal

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_query_length: 5m
  max_query_series: 5000
  max_query_samples: 5000000

querier:
  # No specific querier settings are typically needed for single binary mode beyond limits.
  # default_query_lookback is typically managed by the frontend (Grafana) or limits_config.
  # query_timeout, max_concurrent_queries and engine settings are usually in the `common` or `server` sections
  # or defaults are sufficient for small deployments.
  query_timeout: 1m # Example, ensure this isn't conflicting with anything
  max_concurrent_queries: 20 # Example

ruler:
  storage:
    type: local
    local:
      directory: /tmp/loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://localhost