---
#  loki/config.yaml
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

#  Dit is de top-level storage configuratie
common:
  path_prefix: /tmp/loki
  replication_factor: 1 #  Belangrijk voor single node setup
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-27
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      #  Dit is belangrijk: de periode waarin indices worden gemaakt.
      #  Moet overeenkomen met retention. Hier kun je '24h' zetten als je dat wilt.
      #  Echter, voor boltdb-shipper met filesystem, is de retention_period in 'storage' leidend.
      #  Laten we hem voor nu weghalen, want het is een veelvoorkomende bron van fouten.

#  Definieer de opslag direct onder de root, of onder common (maar common is voor algemene settings)
#  Vaak wordt storage direct onder de top-level geplaatst, naast server en common.
storage:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/cache
    retention_period: 24h
  filesystem:
    directory: /tmp/loki/chunks

#  Component-specifieke configuraties, nu direct onder de root
#  De 'ring' secties voor individuele componenten zijn overbodig als ze al in 'common' staan
#  en als de componenten in een single binary draaien.

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory #  Verwijzing naar common.ring
      replication_factor: 1
      instance_addr: 127.0.0.1
    final_sleep: 0s

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h #  7 dagen

chunk_store_config:
  max_look_back_period: 24h

compactor:
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 15

#  De 'querier' configuratie
querier:
  default_query_lookback: 6h
  query_timeout: 1m
  max_concurrent_queries: 20

#  De 'distributor' en 'ruler' secties zijn vaak niet direct nodig in een basisconfiguratie voor een single binary
#  als ze al de common ring gebruiken. We kunnen ze voor nu weglaten voor simpliciteit.

#analytics:
#   reporting_enabled: false
