# docker-compose.yml
# Definieert de webserver, reverse proxy en API services in een custom netwerk
# Gebruikt omgevingsvariabelen uit het .env bestand

version: '3.8' # Gebruik een recente Docker Compose versie (optioneel, kan verwijderd worden)

services:

  # Service voor de statische webserver
  ${WEB_SERVER_SERVICE_NAME}:
    image: my-web-server2-alpine
    container_name: ${WEB_SERVER_SERVICE_NAME} # Gebruik de variabele voor de containernaam
    build:
      context: ./webserver
      dockerfile: Dockerfile.webserver
    networks:
      - web-network
    restart: always

  # Service voor de backend API applicatie
  ${API_SERVER_SERVICE_NAME}:
    image: my-api-server
    container_name: ${API_SERVER_SERVICE_NAME} # Gebruik de variabele voor de containernaam
    build:
      context: ./api-server
      dockerfile: Dockerfile.api-server
    networks:
      - web-network
    restart: always

  # Service voor de Nginx reverse proxy
  ${REVERSE_PROXY_SERVICE_NAME}:
    image: my-reverse-proxy
    container_name: ${REVERSE_PROXY_SERVICE_NAME} # Gebruik de variabele voor de containernaam
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.reverse-proxy
    ports:
      - "${REVERSE_PROXY_HTTP_PORT}:${REVERSE_PROXY_HTTP_PORT}"   # Map poort 80
      - "${REVERSE_PROXY_HTTPS_PORT}:${REVERSE_PROXY_HTTPS_PORT}" # Map poort 443
    networks:
      - web-network
    restart: always
    depends_on:
      - ${WEB_SERVER_SERVICE_NAME} # Gebruik de variabele voor de afhankelijkheid
      - ${API_SERVER_SERVICE_NAME} # Gebruik de variabele voor de afhankelijkheid

# Definieer het custom netwerk
networks:
  web-network:
    driver: bridge
    name: my-web-platform-network
