# grafana/provisioning/datasources/loki.yaml
apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100 # Verwijzing naar de Loki service in Docker Compose
    isDefault: true
    version: 1
    editable: true
