# promtail/config.yaml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Voeg de servicenaam van Docker Compose toe als label
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service_name
      - source_labels: [__meta_docker_container_name]
        regex: /(.*)
        target_label: container_name
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      # Haal het logpad op
      - source_labels: [__meta_docker_log_stream]
        target_label: log_stream # stderr of stdout
