# .github/workflows/main.yml
# GitHub Actions workflow voor het bouwen, testen en linten van het webplatform

name: Docker Compose CI

permissions:
  contents: read

on:
  push:
    branches:
      - main # Voer de workflow uit bij elke push naar de 'main' branch
  pull_request:
    branches:
      - main # Voer de workflow uit bij elke pull request naar de 'main' branch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint Docker Compose YAML
        # Installeer yamllint en lint de docker-compose.yml
        run: |
          sudo apt-get update && sudo apt-get install -y python3-pip
          pip3 install yamllint
          yamllint docker-compose.yml

      - name: Lint Dockerfiles (Hadolint)
        # Download Hadolint en lint de Dockerfiles
        run: |
          wget -qO- https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 > hadolint
          chmod +x hadolint
          # Gebruik de correcte paden naar de Dockerfiles
          ./hadolint webserver/Dockerfile.webserver
          ./hadolint api-server/Dockerfile.api-server
          ./hadolint reverse-proxy/Dockerfile.reverse-proxy

      - name: Test Nginx Configuration Syntax
        run: |
          # Maak een tijdelijke, compleet Nginx configuratiebestand voor de test
          # Dit omvat de top-level directives (user, events) en het http-blok,
          # zodat de Nginx syntax checker de 'proxy_cache_path' correct valideert.
          echo "user  nginx;" > reverse-proxy/temp_nginx_test.conf
          echo "worker_processes  auto;" >> reverse-proxy/temp_nginx_test.conf
          echo "error_log  /var/log/nginx/error.log warn;" >> reverse-proxy/temp_nginx_test.conf
          echo "pid        /var/run/nginx.pid;" >> reverse-proxy/temp_nginx_test.conf
          echo "" >> reverse-proxy/temp_nginx_test.conf
          echo "events {" >> reverse-proxy/temp_nginx_test.conf
          echo "    worker_connections  1024;" >> reverse-proxy/temp_nginx_test.conf
          echo "}" >> reverse-proxy/temp_nginx_test.conf
          echo "" >> reverse-proxy/temp_nginx_test.conf
          echo "http {" >> reverse-proxy/temp_nginx_test.conf
          # Voeg de inhoud van je reverse_proxy.conf toe aan het http-blok
          cat reverse-proxy/reverse_proxy.conf >> reverse-proxy/temp_nginx_test.conf
          echo "}" >> reverse-proxy/temp_nginx_test.conf

          # Pas de upstream hostnamen aan voor de syntax check binnen de tijdelijke configuratie
          # Deze Seds moeten na de 'cat' komen.
          sed -i 's/server webserver:80;/server 127.0.0.1:80;/' reverse-proxy/temp_nginx_test.conf
          sed -i 's/server api-server:5000;/server 127.0.0.1:5000;/' reverse-proxy/temp_nginx_test.conf

          # Bouw de Nginx linter image (deze blijft hetzelfde)
          docker build -t temp-nginx-linter -f reverse-proxy/Dockerfile.reverse-proxy reverse-proxy/

          # Voer de Nginx syntax test uit met het complete tijdelijke configuratiebestand
          # We mounten temp_nginx_test.conf nu direct als de hoofd nginx.conf voor de test
          docker run --rm -v $(pwd)/reverse-proxy/temp_nginx_test.conf:/etc/nginx/nginx.conf temp-nginx-linter nginx -t -c /etc/nginx/nginx.conf
          
          # Ruim de tijdelijke configuratie op
          rm reverse-proxy/temp_nginx_test.conf

  build-and-test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Load .env file (for local development variables if any)
        run: |
          echo "WEB_SERVER_SERVICE_NAME=webserver" >> $GITHUB_ENV
          echo "API_SERVER_SERVICE_NAME=api-server" >> $GITHUB_ENV
          echo "REVERSE_PROXY_SERVICE_NAME=reverse-proxy" >> $GITHUB_ENV
          echo "REVERSE_PROXY_HTTP_PORT=80" >> $GITHUB_ENV
          echo "REVERSE_PROXY_HTTPS_PORT=443" >> $GITHUB_ENV

      - name: Build and start services
        run: docker compose up -d --build --wait

      - name: Verify Web Server access
        run: |
          echo "Verifying web server access..."
          curl --fail http://localhost
          if [ $? -eq 0 ]; then
            echo "Web server access successful."
          else
            echo "Web server access failed!"
            exit 1
          fi

      - name: Verify API access
        run: |
          echo "Verifying API access..."
          curl --fail http://localhost/api
          if [ $? -eq 0 ]; then
            echo "API access successful."
          else
            echo "API access failed!"
            exit 1
          fi

      - name: List running containers (for debugging)
        if: always()
        run: docker ps -a

      - name: Stop services (cleanup)
        if: always()
        run: docker compose down
